# Site settings
title: Sergio García Prado
email: sergio@garciparedes.me
url: https://garciparedes.me
description: "Software Engineering | Data Science | Research | Scientific Computation"
skills: "Software Engineering | Data Science <br/> Research | Scientific Computation"
meta_author: Sergio García Prado

# Google webmaster tools
google_verify: 'H46a1v6GpJ-90m1n4nAS4yQ5ADvlcz5YTfX5nl1gltk'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: garciparedes

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '9E9E9E'
  primary_rgb: '158,158,158'
  secondary: '616161'
  secondary_dark: '9E9E9E'

# Footer settings
footer:
  copyright: Sergio García Prado
  social: Social Links
  credits: Credits

curriculum_vitae_link: https://garciparedes.me/curriculum-vitae
# cover_letter_link: https://garciparedes.me/cover-letter

description: "Hi everyone! I'm a double Bachelor's degree graduate in Computer Engineering and (future graduate) in Statistics from the University of Valladolid, in Spain. I love to solve complex algorithmic problems, especially those based on Combinatorial Optimization via tricky techniques. Also, I enjoy applying Mathematical and Statistical approaches to solve any kind of problem. I'm curious about Natural Language Processing and Sequential Models. Currently, I'm happily working at Unlimiteck Company Builder."

education:
    -   time: 2019 - 2019
        degree: Erasmus+, Statistics.
        school: <a href="https://www.unibo.it/en" target="_blank">University of Bologna</a>

    -   time: 2017 - 2019
        degree: Bachelor's degree, Statistics.
        school: <a href="http://uva.es" target="_blank">University of Valladolid</a>

    -   time: 2013 - 2017
        degree: Bachelor's degree, Computer Engineering, Computation.
        school: <a href="http://uva.es" target="_blank">University of Valladolid</a>

work:

    -   time: 2018/09 - Present
        title: Software Engineer
        company_name: <a href="https://unlimiteck.com/" target="_blank">Unlimiteck Company Builder</a>

    -   time: 2018/06 - 2018/08
        title: Software Engineer Intern
        company_name: <a href="https://unlimiteck.com/" target="_blank">Unlimiteck Company Builder</a>

    -   time: 2018/03 - 2018/08
        title: Research Assistant Intern
        company_name: <a href="http://uva.es" target="_blank">University of Valladolid</a>

    -   time: 2016/06 - 2016/08
        title: Software Engineer Intern
        company_name: <a href="https://brooktec.com/" target="_blank">Brooktec</a>


nav-links:
  - path: "#about"
    title: "About"
  - path: "#work"
    title: "Work"
  - path: "#education"
    title: "Education"
  - path: "#portfolio"
    title: "Portfolio"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - icon: fab fa-github
    title: Github
    url: https://github.com/garciparedes
  - icon: fab fa-stack-overflow
    title: Stack Overflow
    url: https://stackoverflow.com/users/3921457
  - icon: ai ai-google-scholar
    title: Google Scholar
    url: https://scholar.google.com/citations?user=X3Mb7BAAAAAJ
  - icon: fab fa-linkedin-in
    title: LinkedIn
    url: https://www.linkedin.com/in/garciparedes/
  - icon: fab fa-patreon
    title: Patreon
    url: https://www.patreon.com/garciparedes

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="https://startbootstrap.com/">Start Bootstrap</a>. Improved and adapted by <a target="_blank" href="https://github.com/garciparedes/garciparedes.github.io/commits/master">@garciparedes</a>'

# Build settings
markdown: kramdown
permalink: /:title.html

plugins:
  - jekyll-sitemap


defaults:
  -
    scope:
      path:            "portfolio"
    values:
      sitemap:         false
