# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            garciparedes
tagline:          'Personal Website'
description:      'Computer engineering student, developer, scratcher, beatmaker, gamer and amateur photographer for the time.'
url:              http://garciparedes.github.io

author:
  name:           'Sergio Garcia'
  url:            https://twitter.com/garciparedes

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/garciparedes/garciparedes.github.io