# Site settings
title: Sergio García Prado
email: sergio@garciparedes.me
url: https://garciparedes.me
description: "I'm a junior data { engineer, scientist } with great desire to learn."
skills: "junior data { engineer, scientist }"
meta_author: García Prado Sergio

# Google webmaster tools
google_verify: 'H46a1v6GpJ-90m1n4nAS4yQ5ADvlcz5YTfX5nl1gltk'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: garciparedes

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '9E9E9E'
  primary-rgb: '158,158,158'
  secondary: '616161'
  secondary-dark: '9E9E9E'

# Footer settings
footer:
  copyright: Sergio García Prado
  social: Social Links
  credits: Credits

curriculum-vitae-link: https://nbviewer.jupyter.org/github/garciparedes/curriculum-vitae/blob/master/garciparedes-cv.pdf
cover-letter-link: https://nbviewer.jupyter.org/github/garciparedes/cover-letter/blob/master/garciparedes-cl.pdf

about:
    description: "
      <p>Hi! My name is Sergio and now I’m enrolled in Bachelor’s Degree in Statistics at University of Valladolid, Spain. The reason is because during my Bachelor’s Degree in Computer Engineering the mathematical curiosity arose me. For this reason, I think the merge of my previous engineering knowledge combined with my future scientific learning will enrich me to raise and solve complex problems. In following paragraphs I will describe my professional profile.</p>

      <p>During my first years of coding I’ve learned Java at University, and Android at my home, then I developed EvaluaMeapp. After that, I started to be curious about web development (I really like TypeScript, especially when is boosted with Angular). Also, I’ve worked with PHP and WordPress in during my internship at Brooktec, but I prefer not to work with those technologies anymore.</p>

      <p>In the writing area, I’ve started to use LaTeX as a clean way to submit class assignments in a cleaner way, but it has become in one of my passions. Another of my favourite ways to communicate things (especially when code is involved) is Jupyter Notebook.</p>

      <p>During my Computer’s Engineering Degree last year I focused my work on numerical computation, statistical methods, machine learning algorithms and graph problems. Mostly using Python and libraries like NumPy, Pandas, NetworkX, etc. Also, for my final degree project of Computer Engineering, I’ve started an open source project called TFGraph which consist of a graph library on top of TensorFlow. To learn more about packaging and library distribution I’ve developed ng-katex, an Angular module distributed over npm that allows you to visualize TeX math expressions on browsers boosted by KaTeX.</p>

      <p>Due to my data passion I want to focus my future work on statistical computation, that is everything related with the research and implementation of new techniques of process, analyze and and predict it. For this reason I’ve learned R language and libraries like tidyverse, data.table, etc. Currently, I’m involved in learning amazing things related with probability theory, inference techniques, classification methods, multivariate analysis, etc.</p>

      <p>As you’ve seen I want to work in positions related with Machine Learning, Big Data and Data Analysis. If you’re offering for a related job don’t hesitate to contact me.</p>
      "

    education:

        -   time: 2017 - Present
            degree: Bachelor's degree in Statistics.
            school: University of Valladolid, Spain.

        -   time: 2013 - 2017
            degree: Bachelor's degree in Computer Engineering, Mention in Computation.
            school: University of Valladolid, Spain.
    work:
        -   time: 2018 - Present
            title: Research Assistant (Internship)
            company-name: University of Valladolid, Spain.

        -   time: 2017 (5 months)
            title: Open Source Developer (Final Degree Project)
            company-name: TFGraph

        -   time: 2016 (3 months)
            title: Software Developer (Internship)
            company-name: Brooktec

        -   time: 2015 - 2016
            title: Android Developer (Pet Project)
            company-name: EvaluaMe

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/garciparedes
  - title: stack-overflow
    url: https://stackoverflow.com/users/3921457
  - title: linkedin
    url: https://www.linkedin.com/in/garciparedes/
  - title: medium
    url: https://medium.com/@garciparedes
  - title: trophy
    url: https://www.kaggle.com/garciparedes
  - title: graduation-cap
    url: https://scholar.google.es/citations?user=X3Mb7BAAAAAJ

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Improved and adapted by <a target="_blank" href="https://github.com/garciparedes/garciparedes.github.io/commits/master">@garciparedes</a>'

# Build settings
markdown: kramdown
permalink: /:title.html
