# Site settings
title: Sergio García Prado
email: sergio@garciparedes.me
url: https://garciparedes.me
description: "I'm a junior data { engineer, scientist } with great desire to learn."
skills: "junior data { engineer, scientist }"
meta_author: García Prado Sergio

# Google webmaster tools
google_verify: 'H46a1v6GpJ-90m1n4nAS4yQ5ADvlcz5YTfX5nl1gltk'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: garciparedes

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '9E9E9E'
  primary-rgb: '158,158,158'
  secondary: '616161'
  secondary-dark: '9E9E9E'

# Footer settings
footer:
  copyright: Sergio García Prado
  social: Social Links
  credits: Credits

cv-link: https://nbviewer.jupyter.org/github/garciparedes/cv/blob/master/garciparedes-cv.pdf

about:
    description: "
      <p>Currently, I'm starting a Bachelor's Degree of Statistics at the University of Valladolid. The reason is because of during my Bachelor's Degree of Computer Engineering the mathematical curiosity arose in me. So I think the combination of my previous engineer knowledge with my future scientific learning will be enriching to raise and solve complex problems.</p>

      <p>During my first years of coding I've worked on different projects, related with Android development (like EvaluaMe), TypeScript version of Angular (like D'HondtAnalyzer) or the development of enterprise websites using WordPress (like during my internship at Brooktec). </p>

      <p>But, in the last year I focus my work on numerical computation, statistical results, machine learning algorithms and graph problems. Mostly using Python and libraries like NumPy, Pandas or NetworkX. Also, during my final degree project of Computer Engineering I have used TensorFlow to start a Graph Library on top of it.</p>"

    education:

        -   time: 2017 - Present
            degree: Bachelor's degree in Statistics.
            school: University of Valladolid, Spain.

        -   time: 2013 - 2017
            degree: Bachelor's degree in Computer Engineering, Mention in Computation.
            school: University of Valladolid, Spain.
    work:

        -   time: 2017 (5 months)
            title: Open Source Developer (Final Degree Project)
            company-name: TFGraph

        -   time: 2016 (3 months)
            title: Software Developer (Internship)
            company-name: Brooktec

        -   time: 2015 - 2016
            title: Android Developer (Pet Project)
            company-name: EvaluaMe

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/garciparedes
  - title: stack-overflow
    url: https://stackoverflow.com/users/3921457
  - title: linkedin
    url: https://www.linkedin.com/in/garciparedes/
  - title: medium
    url: https://medium.com/@garciparedes
  - title: trophy
    url: https://www.kaggle.com/garciparedes

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Improved and adapted by <a target="_blank" href="https://github.com/garciparedes/garciparedes.github.io/commits/master">@garciparedes</a>'

# Build settings
markdown: kramdown
permalink: /:title.html
