# Site settings
title: Sergio García Prado
email: sergio@garciparedes.me
url: http://garciparedes.me
description: "I'm student of Computer Engineering with a great desire to learn."
skills: "Junior Computer Scientist"
meta_author: García Prado Sergio

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: garciparedes

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9E9E9E #80B3FF
  primary-rgb: "158,158,158" #"128,179,255"
  secondary: 616161 #FD6E8A
  secondary-dark: 9E9E9E #A2122F

# Footer settings
footer:
  copyright: Sergio García Prado
  location: Location
  social: Around the Web
  credits: Credits

cv-link: http://nbviewer.jupyter.org/github/garciparedes/cv/blob/master/garciparedes-cv.pdf

about:
    description: I'm a student of Computer Engineering with a great desire to learn. I especially like the Computing branch, i.e. data structures, algorithms, and everything related with encoding things.
    education:
        -   time: 2013 - present
            degree: Bachelor's degree in Computer Engineering, Mention in Computation.
            school: University of Valladolid, Spain.
    work:
        -   time: 2016 (3 months)
            title: Software Developer Internship
            company-name: Brooktec

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/garciparedes
  - title: linkedin
    url: https://linkedin.com/in/garciparedes
  - title: send
    url: https://t.me/garciparedes
  - title: twitter
    url: https://twitter.com/garciparedes
  - title: facebook
    url: https://facebook.com/garciparedes


programing-skills:
    - name: Java
      percent: 85
    - name: Python
      percent: 85
    - name: TypeScript
      percent: 70
    - name: Latex
      percent: 95
    - name: Scala
      percent: 50
    - name: C
      percent: 75

interests:
    - name: Cars
      percent: 95
    - name: Cycling
      percent: 75
    - name: Turntablism
      percent: 85
    - name: Rap
      percent: 95
    - name: Logic Problems
      percent: 90
    - name: Cooking
      percent: 70

# Postal address (add as many lines as necessary)
address:
  text: Palencia, Spain
  url:  https://goo.gl/maps/icniv86V1GB2

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Improved and adapted by <a target="_blank" href="https://github.com/garciparedes/garciparedes.github.io/commits/master">@garciparedes</a>'

# Build settings
markdown: kramdown
permalink: pretty
