title : garciparedes
tagline : Development
url : http://garciparedes.github.io
author :
  name : Sergio Garcia
  email : garciparedes@gmail.com
  url : http://garciparedes.github.io
  facebook: garciparedes
  twitter : garciparedes
  linkedin: garciparedes
  github : garciparedes

paginate: 5
pygments : true
baseurl :
permalink : /:title/
relative_permalinks : true
