# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://garciparedes.github.io/
title: garciparedes
email: garciparedes@gmail.com
description: > # 'Computer engineer student, developer, scratcher, beatmaker, amateur photographer and frustrated gamer.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


# This is the list of pages to incldue in the header of the website.
pages_list:       ['Programming', 'Music', 'Photography', 'Downloads' , 'About', 'Archive']

social:
  - title: twitter
    url: https://twitter.com/garciparedes
  - title: github
    url: https://github.com/garciparedes
  - title: linkedin
    url: https://www.linkedin.com/in/garciparedes
